version: '3'

services:
  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: ./.docker/Dockerfile
    container_name: frontend
    command: yarn dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules


  foundry:
    build:
      context: ./foundry
      dockerfile: ./.docker/Dockerfile
    container_name: foundry
    entrypoint: ["/bin/sh", "./.docker/entrypoint.sh"]
    restart: "no"
    volumes:
      - ./foundry:/usr/src/app


  ceramic:
    build:
      context: ./ceramic
      dockerfile: ./.docker/Dockerfile
    container_name: ceramic
    command: npx @ceramicnetwork/cli daemon --config daemon.config.json
    ports:
      - 7007:7007
    volumes:
      - ceramic-data:/root/.ceramic/


  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    ports:
      - 8545:8545
    command: -d -a 100 -e 1000000 -f https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID --database.dbPath /var/lib/ganache/data/ --wallet.accountKeysPath accounts.json
    env_file: .env
    volumes:
      - ganache-data:/var/lib/ganache/data/

volumes:
  node_modules:
  ganache-data:
  ceramic-data:
